botname: 阿晴 #机器人名字
# 禁言时间配置(默认为5)

muteTime: 5
#戳一戳配置
text: 0.3 #文字概率
img: 0.2 #图片概率
voice: 0.1 #语音概率
mu: 0.2 #禁言概率
ex: 0.1 #表情概率
#剩下反击概率 加起来不要大于1
戳一戳群: 
  - 123456

戳一戳: true

ai: false #ai开关,默认false关闭，改成true开启


start_tip: 阿晴上班了,今天又是充满干劲的一天~   #上班提示语  
close_tip: 阿晴去玩了，开溜~      #下班提示语